### ISSUE TITLE
overuse of else if

### ISSUE THREAD

**Issue by avrymi-asraf** [KanerA/pre-course-2021-final#2]
use switch case better readability.

**Comment by listguy** [comment]
@avrymi-asraf Where? Why? How?.
The issue should be more specific

**Comment by DGorgula** [comment]
https://github.com/KanerA/pre-course-2021-final/blob/630fdaaee1ab933a9b7334d74fe20a86ec339916/src/main.js#L215

this is the relevant line of the issue.

all conditions are checking the value of `temp.classList[0]`
@KanerA, perhaps you should use:
`switch(temp.classList[0])`

as @avrymi-asraf suggested.

**Comment by KanerA** [comment]
hey @avrymi-asraf  , thanks for the suggestion.
changed it and working great.
